Repository TOSIT-IO/tdp-collection-extras, pull requests merged in 2023-10, with the labels that each got.

#151 feat(jupyterhub): add sparkmagic kernels
  roles/jupyterhub/server/tasks/config.yml
  roles/jupyterhub/server/tasks/install.yml
  roles/jupyterhub/server/templates/jupyterhub_config.py.j2
  roles/jupyterhub/server/templates/sparkmagic/config.json.j2
  tdp_vars_defaults/jupyterhub/jupyterhub.yml
Labels: enhancement

#153 jupyterhub: add jupyter sessions' persistence on hdfs
  tdp_vars_defaults/jupyterhub/jupyterhub.yml
Labels: jupyterhub

#155 refactor: move hue, jupyterhub and livy observability variables to tdp_cluster.yml
  tdp_vars_defaults/hue/hue.yml
  tdp_vars_defaults/jupyterhub/jupyterhub.yml
  tdp_vars_defaults/livy-spark3/livy-spark3.yml
  tdp_vars_defaults/livy/livy.yml
  tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
Labels: observability
